### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by deini** [preboot/angular-webpack#13]
The description of this repo still mentions `webpack 2` but you reverted those changes.

What's the status of this with webpack 2? :O Why was it reverted? Not ready yet I guess?

----

Also is there a way to run the server + test + watch for changes at the same time? Thanks :dancer:

**Comment by Foxandxss** [comment]
Webpack 2 works nice, the problem is mostly webpack-dev-server and npm2.

With NPM3, all your dependencies are installed in the most *flat* way possible and it won't install any peerDependency. That is good even if the server or the loaders expects an older webpack version (or even 1.x). Those dependencies will suck it and use webpack 2.x as expected.

With NPM2, every dependency will have their own graph of dependencies so the dev-server will at the end use webpack 1.x for it. Luckily the config is 100% backwards compatible but would basically means that you would use webpack 2 but the dev-server run an internal webpack 1 copy that **magically works**. That is bad.

So since we don't want to force the users to NPM3 and the extra feature that we got from webpack 2 is easily reproducible in webpack 1, we decided to revert it.

About your second question. I don't think you can do that.

**Comment by deini** [comment]
Sounds good, thanks a lot for clarifying!

**Comment by Foxandxss** [comment]
anytime.
