### ISSUE TITLE
Just only show the Loading... open with the IDEA

### ISSUE THREAD

**Issue by tancolo** [preboot/angular-webpack#232]
Hello preboot, 
Thank you for your job, It's helpful for me. But I have one question.

When I follow the steps, I just want to build the dist folder. So, I follow these steps.
```
npm install  -> ok
npm build -> ok
```
And then the dist is builded, so I import the project to my IDEA workspace， and I open the index.html using IDEA in the dist folder, but the chrome shows errors,  only the info  " Loading... ".

![open with IDEA](https://cloud.githubusercontent.com/assets/7859533/19954013/f0373d94-a1ae-11e6-9914-46d69708f7ce.png)

![Not Found Errors](https://cloud.githubusercontent.com/assets/7859533/19953880/dc8ff250-a1ad-11e6-871a-48f132b3efc3.png)

But, when I use the `npm start` , and using `localhost:8080` , it works.

So If I want to directly open the index.html with the IDEA, how should I do, to avoid these errors?
Thank you!

**Comment by digitalcraftco** [comment]
I'm having the same problems. After running build... the dist folder is created looks like everything is properly injected to index.html but everything is 404. Locally and on live server environments. This is after cloning repo with no modifications.

**Comment by mcescalante** [comment]
You need to run the `index.html` inside of the `dist/` folder after running `npm build` with a HTTP web server. Importing it to an IDEA workspace (or double clicking to open with Chrome) won't work and will result in "Loading..." forever because the server doesn't know where to find the routes `/js`, `/css`, etc.

If you are looking to test the built site locally, I would suggest installing and using something like node's [http-server](https://www.npmjs.com/package/http-server). It defaults to port 8080 but you can run `http-server -p 8081` to run it on another port easily since this project runs on 8080 by default. Once you run the command, the app should work in your browser.

For production, Apache or nginx works great as a web server, since we're just serving html, css, and js.
