### ISSUE TITLE
Built bundle is huge.

### ISSUE THREAD

**Issue by trusktr** [preboot/angular-webpack#26]
The bundle from `npm start` seems to be over 3 mb. This seems really big. Maybe there's a way to slim it down?

**Comment by Foxandxss** [comment]
That is the raw bundle, all your dependencies in there. This starter itself won't add just like 200kb for the webpack runtime, but the rest are things that you are adding to your application.

**Comment by trusktr** [comment]
The app bundle (generated from this repo with no modifications) is 3.5mb :

![screen shot 2016-05-12 at 2 11 33 pm](https://cloud.githubusercontent.com/assets/297678/15230633/8792694a-184b-11e6-970a-c319b99c3186.png)

That seems really big!

**Comment by Foxandxss** [comment]
I get 1.38mb

![](http://puu.sh/oPFvo/6c4279e395.png)

**Comment by trusktr** [comment]
The huge size is when running with `npm start` (dev mode I suppose). When building with `npm run build`, the resulting bundle is 338K. But in either case I never got 1.38MB. I'm in OS X 10.10.2.

The production `npm run build` size seems to be more reasonable, but I'm still concerned about the dev size. It's humongous!

**Comment by trusktr** [comment]
Hmmm, my webpack output also shows

```
chunk    {0} app.bundle.js (app) 1.38 MB [rendered]
```

which is different than what Chrome is reporting in the network tab.

**Comment by Foxandxss** [comment]
Webpack adds a runtime to the bundle so perhaps that is what is making the file bigger. The important one is the production one.

**Comment by trusktr** [comment]
Downloading to desktop shows the actual file size:

![screen shot 2016-05-12 at 2 28 13 pm](https://cloud.githubusercontent.com/assets/297678/15231066/dc7dbc14-184d-11e6-9016-bc02eb164288.png)


I feel what you're saying, but there must be a way to trim this for dev also (never had it that big before, as far as I can recall). Will be good for older laptops.

**Comment by Foxandxss** [comment]
I am not sure what can be done. I mean, it is just the runtime + angular itself. Nothing else. It is not like the example comes with thousand of non needed things.

**Comment by trusktr** [comment]
It might make sense to run the dedupe plugins for dev also, in case those ever introduce a bug, it'll be caught in dev before prod.

**Comment by trusktr** [comment]
Interesting, docs recommend leaving it for production builds.

**Comment by trusktr** [comment]
Oh well, closing since prod size is reasonable. (but huge dev size seems overkill).

**Comment by simeg** [comment]
This is because webpack is adding the dependencies from `node_modules` into the minified file. In my case I only have one dependency (angular), and I can see the licensing and version info in my minified file. I'm currently trying to figure out a solution.

I tried adding the `webpack-node-externals` dependency and build with it. It removes the dependency from the built file but the built file doesn't work anymore.. If anyone managed to solve this I'd be glad to hear how.

**Comment by simeg** [comment]
So I manage to solve it for my specific case, but it's not the general use case of this app and I'm not sure how to create a generic solution. 

I used this project to generate a development server and to have a build script for an angular directive I've written. This is how my file structure looks like:

```
.
├── ...
├── dev
│   ├── app               # This is angular-webpack
│   └── public            # This is angular-webpack
├── directive.js          # This is my directive
└── ...
```

I said in my previous comment that I think that the problem is that `node_modules` were included in the build step, this is not correct (I think). Instead my problem was that everything in `dev/` were getting included in the build step, and in there I of course have a file which has a `import angular from 'angular'` in it. That's my theory of how how `angular` got into my build file.

I solved this by having different entry points for building and developing in `webpack.config.js`. So it now looks like this:
```
config.entry = {
        app: isProd ? './directive.js' : './dev/app/app.js'
    };
```

I will continue to look into this issue for a bit, hopefully I'll find something. Besides this I've had no problems using this starter/generator, it works great. Thanks!
