### ISSUE TITLE
npm shrinkwrap fails on fresh install

### ISSUE THREAD

**Issue by tsm91** [preboot/angular-webpack#273]
```sh
vagrant@tsm:/workspace/angular2-webpack$ npm shrinkwrap
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "shrinkwrap"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: @angular/compiler@~2.1.1, required by codelyzer@1.0.0-beta.3
npm ERR! peer invalid: @angular/core@~2.1.1, required by codelyzer@1.0.0-beta.3
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/angular2-webpack/npm-debug.log
```

**Comment by jh-code** [comment]
I updated all dependencies with npm-check-updates and then it started working fine.

**Comment by mcescalante** [comment]
Yarn is definitely the best choice for management, and using it really simplifies everything. If you really want to use shrinkwrap, there is a lengthy document with guides/best practices (scroll past the "just use Yarn" update) here: https://github.com/thewoolleyman/npm-shrinkwrap-helper

I am going to close this because it's a bit stale and because with Yarn available and stable now, I don't think anybody is going to put significant effort into getting the more delicate shrinkwrap to work out of the box.
