### ISSUE TITLE
Dist folder is not created / bundle has on browser 3.4 mb???

### ISSUE THREAD

**Issue by mrlove** [preboot/angular-webpack#61]
What do i wrong? Using your sample?

Best,
mrlove

**Comment by phra** [comment]
i'm about to close this ticket because there aren't enough informations. (e.g. the terminal commands that you used to launch the application).
besides of that you can look at `webpack` documentation and `scripts` section of the `package.json` in order to learn the right command to create the production build instead of opening random tickets on github.

**Comment by mrlove** [comment]
Not your day?
