### ISSUE TITLE
crazy slow build and redeploment

### ISSUE THREAD

**Issue by okimchi** [preboot/angular-webpack#71]
Im using this project within docker containes, and it has uge time impact when used in a CI. the build of the container takes more then 20 min, and the redeployment as well, at least 10 min. I was wondering if there is any way to minimize the build time. For example cut most of the npm packages on certain environments.
Thanks.

**Comment by Foxandxss** [comment]
Uhmm, I am afraid that I have no idea at all about docker. Without containers it works fast.

I will see if I knew someone that knows docker that can debug it for me.

You cannot cut packages because they are all needed and the non needed ones I am not really sure if webpack loads them or not (css stuff on test for example).

**Comment by Foxandxss** [comment]
Project changed a bit in a year. Open a new issue if this is still a problem
